Repository shubhamk0027/Cpp-Codes, pull requests merged in 2020-10, with the labels that each got.

#12 Added knapsack with space reduction
  Dynamic Programming/State Space Reduction/Classic knapsack with space reduction.cpp
Labels: enhancement

#13 Multiplication of polynomial using Linked List
  Queues, Stacks And LinkedList/Polynomial multiplication using Linked List.cpp
Labels: enhancement, good first issue

#14 Trees, Graphs with its properties and application of stack and queue are added
  Graph Theory/graph along with common algorithms.cpp
  Queues, Stacks And LinkedList/Queue using Linked List.c
  Queues, Stacks And LinkedList/Queue using array.c
  Queues, Stacks And LinkedList/postfix To Infix Expression using stack.cpp
  Queues, Stacks And LinkedList/prefix To Infix Expression using stack.cpp
  Trees/AVL tree.cpp
  Trees/Largest BST in Binary Tree.cpp
  Trees/segment Tree Blueprint.cpp
Labels: enhancement, hacktoberfest-accepted

#15 Added New standard codes of Tree data structure.
  Trees/BTInversion.cpp
  Trees/Reverse_Level_Order.cpp
  Trees/minDepthofBT.cpp
Labels: enhancement

#16 README and Coursera's Solutions are added
  Courses/competitive_prog_core_skills_coursera/week2_problems/2.1 the cheapest permutation.cpp
  Courses/competitive_prog_core_skills_coursera/week2_problems/2.2 the king.cpp
  Courses/competitive_prog_core_skills_coursera/week2_problems/2.3 sum of minimums.cpp
  Courses/competitive_prog_core_skills_coursera/week2_problems/2.4 expression evaluation.cpp
  Courses/competitive_prog_core_skills_coursera/week3_problems/3.1 compare sums.cpp
  Courses/competitive_prog_core_skills_coursera/week3_problems/3.2 round up.cpp
  Courses/competitive_prog_core_skills_coursera/week3_problems/3.3 yetAnotherSum.cpp
  Courses/competitive_prog_core_skills_coursera/week3_problems/3.4 binaryKnapsack.cpp
  Courses/competitive_prog_core_skills_coursera/week4_problems/4.1 mostFreqSymbol.cpp
  Courses/competitive_prog_core_skills_coursera/week4_problems/4.2 maximal distance.cpp
  Courses/competitive_prog_core_skills_coursera/week4_problems/4.2.1 manhattan.cpp
  Courses/competitive_prog_core_skills_coursera/week4_problems/4.3 multiset.cpp
  Courses/competitive_prog_core_skills_coursera/week4_problems/4.4 maximal sum subarray.cpp
  Courses/competitive_prog_core_skills_coursera/week5_problems/5.1 longestIncreasingSubs.cpp
  Courses/competitive_prog_core_skills_coursera/week5_problems/5.2 EditDistance.cpp
  Courses/competitive_prog_core_skills_coursera/week5_problems/5.3 sumOfDigits.cpp
  Courses/competitive_prog_core_skills_coursera/week5_problems/5.4 makeItSorted.cpp
  Courses/competitive_prog_core_skills_coursera/week6_problems/6.1 Knapsack.cpp
  Courses/competitive_prog_core_skills_coursera/week6_problems/6.2 ChainMatrixMultiplication.cpp
  Courses/competitive_prog_core_skills_coursera/week6_problems/6.3 longestCommonSubsequence.cpp
  Courses/competitive_prog_core_skills_coursera/week6_problems/6.4 maximulSumSquare.cpp
  README.md
Labels: enhancement, good first issue
